// USER
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// CHALLENGE
export const GET_CHALLENGES = "GET_CHALLENGES";
export const GET_CHALLENGE = "GET_CHALLENGE";
export const CREATE_CHALLENGE = "CREATE_CHALLENGE";
export const UPDATE_CHALLENGE = "UPDATE_CHALLENGE";
export const DELETE_CHALLENGE = "DELETE_CHALLENGE";
export const CHALLENGES_LOADING = "CHALLENGES_LOADING";

// ERRORS
export const GET_ERRORS = "GET_ERRORS";
