// AUTH
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT = "LOGOUT";
export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

// CHALLENGE
export const GET_CHALLENGES = "GET_CHALLENGES";
export const GET_CHALLENGE = "GET_CHALLENGE";
export const CREATE_CHALLENGE = "CREATE_CHALLENGE";
export const UPDATE_CHALLENGE = "UPDATE_CHALLENGE";
export const DELETE_CHALLENGE = "DELETE_CHALLENGE";
export const CHALLENGE_ERROR = "CHALLENGE_ERROR";
